### ISSUE TITLE
Suggestion: properties for getting absolute position of an entity

### ISSUE THREAD

**Issue by ivan-mogilko** [tzachshabtay/MonoAGS#267] opened 2018-03-22 01:16 UTC
Currently ITranslateComponent only lets you know one set of coordinates, which is in fact parent-relative coordinates (although comments tell they are room coordinates, but that's true only when object has no parent).
At the same time API does not provide a way to get absolute (room) coordinates of an entity.

When that may be useful: many kind of situations - collision checking for instance, - but most easy example is camera targetting. By the way, right now default camera has a related bug: it does not take object's parents into account (which may be also added as a separate ticket).

My suggestion is to add following properties:
* float AbsoluteX
* float AbsoluteY
* (not sure) ILocation AbsoluteLocation.

Common implementation would be to sum up current entity's XY coords with each parent along the tree upwards (if anchors are implemented (#245), this should also take them into account).

I was in doubts what interface to put these though. ITranslate is the first that comes to mind, but then, it does not necessarily belong to something that may have parent. OTOH maybe that's not a big deal (we may assume that in enviroment where you don't have entity trees local and absolute coordinates always match).
The only alternative that comes to mind is IInObjectTreeComponent, or even IInTree<T>. But that not necessary something that may have location, so could be even worse option.

Finding a place to implement it seem also a bit complicated. If these properties are in ITranslate , then AGSTranslateComponent is again the first option, but the issue is that it should bind to IInTree somehow, and idk if it's possible to do that without knowing actual end type of an entity. And IInObjectTreeComponent seem too specific to put into ITranslate implementation.

**Comment by tzachshabtay** [comment] 2018-03-22 02:18
Isn't this a duplicate of #149 ?

> At the same time API does not provide a way to get absolute (room) coordinates of an entity.

`GetBoundingBoxes(viewport).HitTestBox` gives you the absolute room coordinates. Note that the API here is not ideal- you don't really need to pass the viewport as the hit test box is the same for all viewports, it's just that the bounding boxes also contain the render box which is unique to the viewport.

> I was in doubts what interface to put these though.

I was thinking of having a separate component for this.

**Comment by ivan-mogilko** [comment] 2018-03-22 14:24
> Isn't this a duplicate of #149 ?

In #149 you say:

> I was thinking of adding a boolean value that would tell engine how the position should be interpreted (local or absolute).

Which means that X,Y could be either relative or absolute?

What I propose is a way to get absolute coordinates regardless of whether childrens position is interpreted as local or absolute.

**Comment by tzachshabtay** [comment] 2018-03-22 15:06
Well, that was the original thinking, but then you mentioned in your comment the absolute position property, which is the same as what you suggest here, and I find it's a duplicate in the sense that we'll either do this or that, but not both, they aim to solve pretty much the same problem.

Anyway, if it's just about getting the absolute position (as opposed to setting it, which #149 aims to give a solution to), then GetBoundingBoxes has you covered, with the exception that you get a complete rectangle and not a single point. 
And if you want to apply the pivot to get a single point from the box, then I think interpolating along the edges of the bounding boxes should do the trick, and no reason to do it in an IObject extension method when we can do it in a component which can be applied to more entities.

I guess we can keep this issue open just to do the getter, and leave the setter for the other issue (the setter is much more complicated to implement, we basically need to invert all of the matrices up the chain).

**Comment by ivan-mogilko** [comment] 2018-03-22 15:21
These properties may have setters too. It's just that I was not sure what you may want the boolean switch for, because it seem to have different effect. Since most code will probably work with just X and Y properties, switching the meaning of these may change the looks of the game a lot.

AbsoluteX/Y properties are more explicit, so you can use them when you're sure you want to change absolute position regardless of what the object is attached to.

> Anyway, if it's just about getting the absolute position (as opposed to setting it, which #149 aims to give a solution to), then GetBoundingBoxes has you covered,

Uhhh, to be frank, I don't like to use this API to just get two coordinates, that's all. But I could make a helper methods in my game which just return X and Y.

And yes, I completely forgot about taking parent rotation into account...

**Comment by ivan-mogilko** [comment] 2018-03-22 15:58
Hmm... just realized that bounding box may be actually more convenient for camera centering and other things than position. For camera you may get center of the box.

**Comment by tzachshabtay** [comment] 2018-03-22 16:46
Ok, so I'm closing this issue in favor of #149 which will cover that property with both a getter and a setter. If you end up feeling that you do want a getter soon, comment and I'll re-open (as coding the getter will be much easier than the setter). Otherwise this will probably sit in the backlog for a while, as I don't consider it a high priority.

**Closed by tzachshabtay** 2018-03-22 16:46 UTC

**Comment by ivan-mogilko** [comment] 2018-03-22 17:43
Question, would it be acceptable to modify default camera to get target x,y as following:
<pre>
AGSBoundingBox hitBox = target.GetBoundingBoxes(viewport).HitTestBox;
float targetX = (hitBox.MaxX + hitBox.MinX) / 2;
float targetY = (hitBox.MaxY + hitBox.MinY) / 2;
</pre>
