### ISSUE TITLE
Viewport pivot feature not working as expected

### ISSUE THREAD

**Issue by ivan-mogilko** [tzachshabtay/MonoAGS#264] opened 2018-03-20 22:21 UTC
After updating games to changes from #260 scaling and rotating are completely broken. I cannot even tell what point it scales from or rotates around. From the looks of it, it lies far beyond the viewport itself.

The game room is very large, may that be related somehow?

**UPD**. While pivot is at 0,0 it definitely looks like it rotates and scales related to the bottom-left of the room. If I change it to 0.5,0.5, I am not so sure what happens. Maybe the center point becomes a point lying at a distance of half-viewport size from the room's corner (not certain).

Another problem is that if I change pivot to, for example (0.5, 0.5) the viewport is no longer centered to the camera target, the target appears in the bottom-left corner instead. Is this supposed to be like that?

**Comment by tzachshabtay** [comment] 2018-03-21 02:38
I've made some fixes in this branch: https://github.com/tzachshabtay/MonoAGS/tree/ViewportFixes
Can you test it and confirm it works as expected now?

**Comment by tzachshabtay** [comment] 2018-03-21 16:31
> Maybe treat all viewport positioning in relation to pivot?

Yes, that's what I wanted to do in the beginning, actually, only messed up the signs. 
This way it will be consistent with how the pivot works for the objects.
I'll do another commit today for this.

> rotation still performed around a fixed room point rather than relative to viewport position.

Hmmm, it works fine in the demo game, you can see in Features -> Viewports, it has a viewport with (0.5, 0.5) pivot and it's rotated around the center as expected.
I'll try to reproduce with "Last & Furious" (I assume that's where you saw this?).

**Comment by ivan-mogilko** [comment] 2018-03-21 16:54
>I'll try to reproduce with "Last & Furious" (I assume that's where you saw this?).

Yes, I was testing this in racing game, because I have viewport rotation bound to key controls there already.

But I guess it could be more convenient to make a room x2 or x3 size of a game's virtual size and test it there, probably that would be easier to see what point it rotates around. Because in L&F I have to drive down to the bottom of the map to actually confirm that viewport rotates around some location in the corner.

**Comment by tzachshabtay** [comment] 2018-03-22 04:06
Pushed fixes again (same branch), can you re-test? Thanks.

**Comment by ivan-mogilko** [comment] 2018-03-22 16:36
Ok, rotation works now, rotates around pivot.

But scaling now zooms in/out relative to bottom-left corner, or so it seems.

**Comment by tzachshabtay** [comment] 2018-03-22 16:49
I'll need a repro for this, then, because I tested with Last & Furious (after changing the viewport pivot to 0.5,0.5 and the camera to adjust to that pivot), and both scaling and rotating were centered as expected.

**Comment by ivan-mogilko** [comment] 2018-03-22 17:07
I pushed a temporary branch: https://github.com/ivan-mogilko/MonoAGSGames/tree/fix--camerapivot

Removed viewport position clamping to room bounds from camera, because it made it harder to test.

**Comment by tzachshabtay** [comment] 2018-03-23 03:12
Thanks, should be fixed now, can you confirm on your side?

**Comment by ivan-mogilko** [comment] 2018-03-23 08:08
Ok, it works now!

**Closed** 2018-03-23 13:31 UTC
Labels: bug
